#!/usr/bin/env bash
apt-get update
apt-get install -y git curl fish
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install > /tmp/install_omf
fish /tmp/install_omf --noninteractive && rm /tmp/install_omf
# https://stackoverflow.com/questions/866989/fish-interactive-shell-full-path
echo "set -U fish_prompt_pwd_dir_length 0" | fish
echo "omf install agnoster" | fish

echo "set -g fish_greeting" >> ~/.config/fish/config.fish

apt-get install -y zoxide
echo "zoxide init fish | source" >> ~/.config/fish/config.fish

cat ~/.config/fish/config.fish
