#!/usr/bin/env bash

read -p "ALIAS: " ALIAS
read -p "S3_SERVER: " S3_SERVER
read -p "S3_USER: " S3_USER
read -p "S3_PASSWORD: " S3_PASSWORD

echo mc config host add $ALIAS $S3_SERVER $S3_USER $S3_PASSWORD
read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    mc config host add $ALIAS $S3_SERVER $S3_USER $S3_PASSWORD
fi
